GhActions(Pi): add checkout
In order to try to fix this error:
```

> pi-action@1.9.2 prepare
> prek install --allow-missing-config --hook-type pre-commit --hook-type commit-msg --hook-type prepare-commit-msg --hook-type pre-push

error: Command `get git hooks dir` exited with an error:

[status]
exit status: 128

[stderr]
fatal: not a git repository (or any of the parent directories): .git

npm error code 2
npm error path /home/runner/work/_actions/knocte/pi-action/main
npm error command failed
npm error command sh -c prek install --allow-missing-config --hook-type pre-commit --hook-type commit-msg --hook-type prepare-commit-msg --hook-type pre-push
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2026-06-10T16_52_26_910Z-debug-0.log
Error: Process completed with exit code 2.
```