Retry on any HttpRequestException in CustomHttpClient
And not only on timeout.

This will make provider keep trying in case of temporary
connectivity issues, instead of failing with errors like:
```
error: One or more errors occurred. (The SSL connection could not be established, see inner exception.)
```